LIBFREETYPE_CFLAGS = `freetype-config --cflags`
LIBFREETYPE_LDFLAGS = `freetype-config --libs`

-include $(root)/freetype/Makefile.conf

CFLAGS += $(LIBFREETYPE_CFLAGS)
LDFLAGS += $(LIBFREETYPE_LDFLAGS)
